### ISSUE TITLE
Missing Object.assign polyfill for IE

### ISSUE THREAD

**Issue by schuma7** [smeijer/redux-define#4]
I just added this neat little library to my current Next.js project and noticed that the app was not working on IE10 and 11 anymore. Apparently this is due to the usage of Object.assign which needs to be polyfilled for Internet Explorer. I quickly wanted to ask if you have any plans of adding support for  IE browsers by adding the necessary Babel transform to the project?

**Comment by smeijer** [comment]
Yes, IE should be supported. 

It would be really nice if you're able and willing to fix this trough a PR.

**Comment by schuma7** [comment]
@smeijer did you have the chance to review the changes? Would kind of need to incorporate that change for the upcoming launch in a week, would be cool if you find the time to release a new version on npm, if you're happy with the PR.

**Comment by smeijer** [comment]
Sorry for the late response. The PR was looking just fine. So I merged it, and published a patch release. `v1.1.1` contains your submitted changes.

I hope it is in time for your upcoming launch. Is it a opensource thing or private thing you're launching? (just me being curious)

**Comment by schuma7** [comment]
No worries, I've just updated the version and it's all working!

Yes, the launch date is not in jeopardy ;-). It's for a client project of mine which unfortunately is not open-sourced.
