### ISSUE TITLE
Add typings to Definitly-Typed

### ISSUE THREAD

**Issue by levino** [smeijer/redux-define#7]
It would be nice if there there typescript typings under `@types/redux-define`

**Comment by eoshardwork** [comment]
jest error because of TS7016
```
$ jest
 FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

error TS7016: Could not find a declaration file for module 'redux-define'. '/xxxx/rn-template/node_modules/redux-define/lib/index.js' implicitly has an 'any' type.
      Try `npm install @types/redux-define` if it exists or add a new declaration (.d.ts) file containing `declare module 'redux-define';`

    1 import * as defineAction from 'redux-define';
```

**Comment by levino** [comment]
@eoshardwork You find instructions on how to fix this in the logs. `@types/redux-define` does not exist so you have to add a declaration file yourself. No reason to post this here, please read up on how to write and use custom declaration files for your TypeScript project in the TypeScript docs.

@smeijer I think this should be closed as wontfix. If anyone wants to have DT types (which would be the package `@types/redux-define`) they have to write them and bring it to the [DT repo](https://github.com/DefinitelyTyped/DefinitelyTyped). This project exists to relieve maintainers of pure Javascript projects from discussing TypeScript specific issues. If you do not use TypeScript yourself, tell people to go to DT and close issues about TS here.

For everyone else: There are better packages than `redux-define`, especially if you use TypeScript. I like [`typed-actions`](https://github.com/lttb/typed-actions) and I stopped using `redux-define` soon after I discovered the other package (sorry to be so blunt @smeijer). This is also why I never came back to this issue here, which I will close now.

**Comment by smeijer** [comment]
Thanks for the comment @Levino!

No hard feelings about being blunt. I stopped using `redux` myself, so I also no longer use `redux-define`.

I agree with the statement that if people want typings (which I can imagine), that they can submit them to definitely-typed.

---

That being said, I've taken a look at `typed-actions`, but fail to see how it's an alternative for `redux-define`. I think they have different goals, and are complementary?

From their readme:

```js
/**
 * Declare Action Types as constants and export them
 */
export const UPDATE = '@namespace/UPDATE'
export const UPDATE_FULFILLED = '@namespace/UPDATE_FULFILLED'
export const UPDATE_FAILED = '@namespace/UPDATE_FAILED'
```

The idea of `redux-define`, is to make those codeblocks obsolete:

```js
export const UPDATE = defineAction('UPDATE', ['FULFILLED', 'FAILED'], '@namespace');

// result:
console.log('' + UPDATE);            // @namespace/UPDATE
console.log('' + UPDATE.FULFILLED);  // @namespace/UPDATE_FULLFILLED
console.log('' + UPDATE.FAILED);     // @namespace/UPDATE_FAILED
```

Combined ([example from their readme](https://github.com/lttb/typed-actions/blob/a915728285c0f4eedbf4a43bc0b32f40c486c9c1/README.MD#actions)):

```diff
import { createActions, action, empty } from 'typed-actions';
+ import { defineAction } from 'redux-define';
import type { EntityId } from '../types';

/**
 * Declare Action Types as constants and export them
 */
- export const UPDATE = '@namespace/UPDATE'
- export const UPDATE_FULFILLED = '@namespace/UPDATE_FULFILLED'
- export const UPDATE_FAILED = '@namespace/UPDATE_FAILED'
+ export const UPDATE = defineAction('UPDATE', ['FULFILLED', 'FAILED'], '@namespace');

/**
 * Create Actions Collection
 */
const actions = createActions({
    /**
     * { type: UPDATE }
     */
-   [UPDATE]: empty,
+   [UPDATE]: empty,

    /**
     * { type: UPDATE_FULFILLED, payload: EntityId[] }
     */
-   [UPDATE_FULFILLED]: (x: EntityId[]) => action(x),
+   [UPDATE.FULFILLED]: (x: EntityId[]) => action(x),

    /**
     * { type: UPDATE_FAILED, payload: EntityId, meta: { sync: true } }
     */
-   [UPDATE_FAILED]: (x: EntityId) => action(x, { sync: true }),
+   [UPDATE.FAILED]: (x: EntityId) => action(x, { sync: true }),
})
```

In this compact example, redux-define is able to remove 2 lines. Those two lines aren't much and don't seem to be worth the trouble. But it adds up over time when having more than 1 action. Also see [here](https://github.com/smeijer/redux-define#why-use-redux-define)

**Comment by HenriqueDerosa** [comment]
I am not sure this is what @Levino meant, or you answered the question. I think it's more related to - using you example, @smeijer - have an auto completion when we write `UPDATE.`, and we know that we can use FULFILLED or FAILED, for instance. Isn't it the issue? I'm not sure cause I use @types stuff to do this.

**Comment by ensconced** [comment]
I just opened a PR to add some types here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60459. Just in case anyone feels like reviewing!

EDIT: This has now been merged and the package `@types/redux-define` is available on npm
